- .travis.yml
Set environment variable GITHUB_TOKEN on travis-ci.
> Updated travis.yml with github pages #25

- CHANGELOG.md
- README.md
- e2e/infrastructure/NamespaceHttp.spec.ts
- package-lock.json
- package.json
- src/infrastructure/NamespaceHttp.ts
- src/model/UInt64.ts
- src/model/model.ts
- src/model/mosaic/Mosaic.ts
- src/model/mosaic/MosaicId.ts
- src/model/mosaic/MosaicNonce.ts
- src/model/mosaic/NetworkCurrencyMosaic.ts
- src/model/mosaic/NetworkHarvestMosaic.ts
- test/model/UInt64.spec.ts
- test/model/mosaic/MosaicId.spec.ts
- test/model/mosaic/MosaicNonce.spec.ts
- test/model/mosaic/NetworkCurrencyMosaic.spec.ts
- test/model/mosaic/NetworkHarvestMosaic.spec.ts
- test/model/transaction/LockFundsTransaction.spec.ts
- test/model/transaction/SecretLockTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
- Added MosaicNonce unit tests 
- Added MosaicNonce.createRandom() 
- Added MosaicId.createRandom(owner)
- Added MosaicId.createFromNonce(nonce, owner)
> MosaicId and MosaicNonce usability improvement

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Version upgrade from 0.10.1 for Alpace compatibility, to 0.11 for cow compatibility.
> v0.11: cow compatibility upgrade for SDK

- package-lock.json
- package.json
- Added `TransactionMapping` (fixes #56 )
- Added `CreateTransactionFromPayload` (fixes #56 )
- Added `SerializeTransactionToJSON`
- Added several `toDTO()` methods for serialization (fixes #56 )
- Added `multisigAccountAdded` in Listener
- Added `accountAddedToMultisig` in Listener
> v0.11.2: exposed serialization methods (issue #56)

- src/model/transaction/LockFundsTransaction.ts
- src/model/transaction/SecretLockTransaction.ts
- src/model/transaction/SecretProofTransaction.ts
update UInt64.fromUint(0) to  new UInt64([0, 0]), code consistency
> update transaction init fee

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/CreateTransactionFromPayload.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/mosaic/MosaicProperties.ts
- src/model/transaction/PlainMessage.ts
- src/model/transaction/Transaction.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/model/transaction/PlainMessage.spec.ts
Issue: #107 
Fixed a few issues with createFromDTO
> Fixed #107 - Fixed issues on createFromDTO with JSON payload

- src/infrastructure/QueryParams.ts
SDK side fix for https://github.com/nemtech/catapult-rest/issues/21
:warning: the e2e tests do not work I think
> Fix message parsing when TransferTransaction has not message property

- src/infrastructure/model/models.ts
Fixed ResolutionStatementDTO copied into enumsMap bug
> Issue #177 ResolutionStatementDTO copied into enumsMap

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Added NodeHttp
- Fixed null mosaic property in MosaicHttp
- Fixed Uint8 conversions (control char added)
- Fixed ResolutionStatementDTO in exports
> v0.12.3: Stability fixes for Dragon update

- src/core/crypto/index.ts
Issue #187 exposed SHA3Hasher and NACL classes
> Issue #187 exposed SHA3Hasher and NACL classes

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Added export for Sha3Hasher
- Added export for nacl_catapult
- Added changelog milestone attribution
> v0.12.4: Added export for Sha3Hasher and nacl_catapult

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Elephant
- Added Mosaic Restriction (New models and transactions)
- Fixed RXJS compatibility issue (after run `npm update`)
- Fixed `signTransactionGivenSignatures` signature not verified issue
- Fixed version texts in Readme.md
> V0.13.1: RXJS upgrade and other small fixes

- e2e/infrastructure/MosaicHttp.spec.ts
- src/core/format/Utilities.ts
- src/infrastructure/MosaicHttp.ts
Updated `this.Encoded_Block_Size` to just `Encoded_Block_Size` in decodeBlock
> Bug fixed in Utilities.ts - Encoded_Block_Size

- src/model/transaction/AggregateTransaction.ts
- test/model/transaction/AggregateTransaction.spec.ts
Added `addTransactions` to aggregate transactions
Issue: #229
> Added `addTransactions` to aggregate transactions

- .gitignore
- src/infrastructure/Listener.ts
- src/model/transaction/MosaicGlobalRestrictionTransaction.ts
- Fixed #245 #268 due do E3 schema changes
- Fixed #267 missing extra modify multisig account filter implementation.
- Fixed #270 MosaicGlobalRestriction js doc typo
> WS listener cosignatory and block channel issue and other small issues fixes

- src/model/transaction/AccountRestrictionTransaction.ts
- src/model/transaction/AddressAliasTransaction.ts
- test/model/transaction/AccountRestrictionTransaction.spec.ts
- JSDOC typo fixe #298 
- OperationRestriction filter list typo fixed #299
> JAV-65, JAV-66 Small issues fixed

- src/infrastructure/receipt/CreateReceiptFromDTO.ts
- src/model/namespace/AddressAlias.ts
- src/model/namespace/Alias.ts
- src/model/namespace/EmptyAlias.ts
- src/model/namespace/MosaicAlias.ts
- src/model/receipt/ArtifactExpiryReceipt.ts
- src/model/receipt/BalanceChangeReceipt.ts
- src/model/receipt/BalanceTransferReceipt.ts
- src/model/receipt/InflationReceipt.ts
- src/model/receipt/Receipt.ts
- src/model/receipt/ReceiptSource.ts
- src/model/receipt/ResolutionEntry.ts
- src/model/receipt/ResolutionStatement.ts
- src/model/receipt/TransactionStatement.ts
- test/infrastructure/receipt/CreateReceiptFromDTO.spec.ts
- test/model/receipt/Receipt.spec.ts
- Fixed bug in `ResolutionStatement` & `ResolutionEntry`
- Added `ResolutionType` parameter in to `ResolutionEntry`
- Added Receipt serializer 
- Added `generateHash` to generate receipt hash for merkle tree proof
- Updated `CreateReceiptFromDTO`
- Added/Fixed receipt tests
> JAV-41 Audit merkle proof receipt

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Fixed `AddressAlias` deserialization issue.  Resolved namespaceId using little endian encoding from rest payload
- Fixed `MosaicSupplyChangeTransaction` schema issue. Changed `Direction` to `Action`
> v0.14.2 release

- e2e/service/MetadataTransactionService.spec.ts
- src/core/format/Convert.ts
- src/service/MetadataTransactionService.ts
- test/service/MetadataTransactionservice.spec.ts
- Fixed bug in MetadataTransactionService delta data bug
issue: #313
> JAV-72 MetadataTransactionService delta value

- src/core/format/RawAddress.ts
- src/core/utils/UnresolvedMapping.ts
- src/model/receipt/BalanceTransferReceipt.ts
- src/model/receipt/ResolutionStatement.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/model/transaction/TransferTransaction.ts
- test/core/utils/UnresolvedMapping.spec.ts
- test/model/receipt/Receipt.spec.ts
Fixes https://nem.atlassian.net/browse/TS-76 / https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/318
> TS-76 - aliasToRecipient serialization depends on the network type

- src/core/format/Convert.ts
- src/model/message/PlainMessage.ts
- src/model/model.ts
- Exported `EmptyAlias`
- make `decodeHex` public
Issue: #316 #317
> TS-74, TS-75 expose internal classes and method

- src/model/UInt64.ts
- test/model/UInt64.spec.ts
Added `UInt64.compare()` method
Issue #347
> Added Uint64.compare

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.2
- Applied latest `Fushicho2` schema changes to both transaction serialization and http client codes.
- Added `addCosignatures` method for filling cosignatures offline.
- Added `compare` function in UInt64 class for unsigned 64 bytes numbers comparison.
> v0.15.0 release

- src/model/transaction/Deadline.ts
- Changes the Deadline.timestampNemesisBlock property to be 0.9.1.1 compatible
> fix newly added epochAdjustment

- test/model/mosaic/MosaicNonce.spec.ts
> issue#373: use Uint8Array comparison for toDTO() with Uint8Array return type

- src/infrastructure/Listener.ts
Removed console.log in listener
> Fixed #388 Removed listener console.log

- src/model/mosaic/MosaicNonce.ts
- test/model/mosaic/MosaicNonce.spec.ts
This fix is for MosaicNonce.createFromHex param.
> Add MosaicNonce#toHex()

- package-lock.json
- package.json
- src/model/node/RoleType.ts
Fixes issue https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/437
Updated open api generated lib 0.7.22
> Added role type Dual Node

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/NamespaceMosaicIdGenerator.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/mosaic/MosaicInfo.ts
- src/model/mosaic/MosaicNonce.ts
- src/model/transaction/MosaicDefinitionTransaction.ts
- test/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- test/model/mosaic/MosaicNonce.spec.ts
> Changed mosaicNonce to uint32 in dto

- e2e/infrastructure/IntegrationTestHelper.ts
- src/infrastructure/Http.ts
- src/infrastructure/NetworkHttp.ts
- src/infrastructure/NodeHttp.ts
- src/service/BlockService.ts
- src/service/TransactionService.ts
- src/service/interfaces/ITransactionService.ts
- test/infrastructure/NetworkHttp.spec.ts
- test/infrastructure/NodeHttp.spec.ts
- test/service/TransactionService.spec.ts
Added TransactionService Unit Tests
Improved e2e tests to use TransactionService announce
Fixed BlockService class not implementing the interface and deprecated calls
Fixes issue https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/468
> Added WS status error handling to TransactionService

- src/model/mosaic/MosaicNonce.ts
- test/model/mosaic/MosaicNonce.spec.ts
- Added padding in mosaicNonce.createFromHex
Fixed #474
> Added padding in mosaicNonce.createFromHex

- e2e/infrastructure/AccountHttp.spec.ts
- e2e/infrastructure/MosaicHttp.spec.ts
- package-lock.json
- src/core/format/Convert.ts
- src/infrastructure/Http.ts
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/model/mosaic/MosaicId.ts
- src/model/mosaic/MosaicNonce.ts
- src/model/transaction/MosaicDefinitionTransaction.ts
- src/service/TransactionService.ts
- test/core/format/Convert.spec.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/NodeHttp.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/model/mosaic/MosaicId.spec.ts
- test/model/mosaic/MosaicNonce.spec.ts
- test/model/transaction/AggregateTransaction.spec.ts
- test/model/transaction/MosaicDefinitionTransaction.spec.ts
- Changed http exception handling so the error body is in the exception
- Some code improvements around how MosaicNonce objects are created
> Changed dto mappers to map nonce as a decimal int.

- src/infrastructure/AccountHttp.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/ChainHttp.ts
- src/infrastructure/MetadataHttp.ts
- src/infrastructure/MosaicHttp.ts
- src/infrastructure/MultisigHttp.ts
- src/infrastructure/NamespaceHttp.ts
- src/infrastructure/NetworkHttp.ts
- src/infrastructure/NodeHttp.ts
- src/infrastructure/ReceiptHttp.ts
- src/infrastructure/RestrictionAccountHttp.ts
- src/infrastructure/RestrictionMosaicHttp.ts
- src/infrastructure/TransactionHttp.ts
- test/model/mosaic/MosaicId.spec.ts
> useQuerystring in http client on AccountRoutesApi

- .travis.yml
- travis/release.sh
Added escape skip flag to avoid republishing the same version
> Fixed github token env variable name

- package-lock.json
- package.json
> Updated Minimist package

- package-lock.json
- package.json
> OpenAPI 0.8.9

- e2e/infrastructure/TransactionHttp.spec.ts
- package-lock.json
- package.json
- src/core/utils/LockHashUtils.ts
- src/core/utils/utility.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/model.ts
- src/model/transaction/LockHashAlgorithm.ts
- src/model/transaction/SecretLockTransaction.ts
- src/model/transaction/SecretProofTransaction.ts
- test/core/utils/Hashes.spec.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/model/transaction/HashTypeLengthValidator.spec.ts
- test/model/transaction/SecretLockTransaction.spec.ts
- test/model/transaction/SecretProofTransaction.spec.ts
- Added LockHashUtils
- Removed Op_Keccak_256 algorithm
- Renamed HashType to LockHashAlgorithm
- Renamed model field name to be aligned with Catbuffer
- Fixed security alert on `kind-of`
Fixed #518
Fixed #521
> LockHashAlgorithm

- e2e/infrastructure/AccountHttp.spec.ts
- e2e/infrastructure/BlockHttp.spec.ts
- e2e/infrastructure/IntegrationTestHelper.ts
- e2e/infrastructure/Listener.spec.ts
- e2e/infrastructure/NamespaceHttp.spec.ts
- e2e/infrastructure/TransactionHttp.spec.ts
- Added networkCurrency resolver for e2e tests
Fixed #523
> Added networkCurrency resolver for e2e tests

- src/model/transaction/AccountMetadataTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/NamespaceMetadataTransaction.ts
- test/core/utils/TransactionMapping.spec.ts
- test/model/mosaic/MosaicNames.spec.ts
- test/model/transaction/AccountMetadataTransaction.spec.ts
- test/model/transaction/MosaicMetadataTransaction.spec.ts
- test/model/transaction/NamespaceMetadataTransaction.spec.ts
- Removed metadata size validation
Fixed #526
> Removed metadata size validation

- src/model/account/Account.ts
- src/model/account/PublicAccount.ts
- src/model/wallet/SimpleWallet.ts
- test/core/crypto/utilities.spec.ts
- test/model/account/Account.spec.ts
- test/model/account/PublicAccount.spec.ts
- test/model/wallet/SimpleWallet.spec.ts
> Added check on  Account.signData and PublicAccount.verifySignature for hexadecimal

- package-lock.json
- src/model/transaction/AggregateTransaction.ts
- src/model/transaction/Transaction.ts
- src/service/AggregateTransactionService.ts
- test/model/transaction/AggregateTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
- test/service/AggregateTransactionService.spec.ts
- Added setMaxFeeForAggregate
- Changed setMaxFee for stand alone tx only
- Added getMaxCosignatures
- Added getNetworkMaxCosignaturesPerAggregate
Fixed #533
> maxFee in Aggregate transactions

- src/service/AggregateTransactionService.ts
- test/model/mosaic/MosaicAmountView.spec.ts
- test/service/AccountService.spec.ts
- test/service/AggregateTransactionService.spec.ts
> Return distinct cosignature count in aggregateTransactionService

- e2e/infrastructure/TransactionHttp.spec.ts
- package-lock.json
- package.json
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/transaction/AccountKeyLinkTransaction.ts
- test/core/utils/TransactionMapping.spec.ts
- test/core/utils/TransactionMappingWithSignatures.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/infrastructure/TransactionHttp.spec.ts
- test/model/transaction/AccountKeyLinkTransaction.spec.ts
- Patched with latest catbuffer and openAPI
Fixed #575
> Patched with latest catbuffer and openAPI

- src/infrastructure/Listener.ts
> Fixed bug on ws listener status

- e2e/infrastructure/Listener.spec.ts
- src/infrastructure/IListener.ts
- src/infrastructure/Listener.ts
- src/model/blockchain/FinalizedBlock.ts
- src/model/model.ts
- test/infrastructure/Listener.spec.ts
> Added finality websocket codes

- e2e/infrastructure/NodeHttp.spec.ts
- package-lock.json
- package.json
- src/infrastructure/NodeHttp.ts
- src/infrastructure/NodeRepository.ts
- test/infrastructure/NodeHttp.spec.ts
Fixed issued in unlocked account
> Updated openAPI spec for unlockedAccount

- src/core/utils/DtoMapping.ts
- test/core/utils/DtoMapping.spec.ts
> Server duration parser and test refactor

- CHANGELOG.md
- package-lock.json
- package.json
- src/infrastructure/FinalizationHttp.ts
- src/model/finalization/BmTreeSignature.ts
- test/infrastructure/FinalizationHttp.spec.ts
* Patched the finalization schema
* update openAPI
> Patched the finalization schema (#740)

- package-lock.json
- package.json
- src/infrastructure/ReceiptHttp.ts
- src/infrastructure/searchCriteria/TransactionStatementSearchCriteria.ts
- test/infrastructure/ReceiptHttp.spec.ts
Added from / to height in receipt search
> Added from / to height in receipt search

- src/infrastructure/Listener.ts
- src/model/namespace/NamespaceId.ts
- src/model/transaction/AccountAddressRestrictionTransaction.ts
- src/model/transaction/AccountKeyLinkTransaction.ts
- src/model/transaction/AccountMetadataTransaction.ts
- src/model/transaction/AggregateTransaction.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/MultisigAccountModificationTransaction.ts
- src/model/transaction/NamespaceMetadataTransaction.ts
- src/model/transaction/SecretLockTransaction.ts
- src/model/transaction/SecretProofTransaction.ts
- src/model/transaction/Transaction.ts
- src/model/transaction/TransferTransaction.ts
- test/infrastructure/Listener.spec.ts
- test/model/transaction/AccountMetadataTransaction.spec.ts
- test/model/transaction/AccountRestrictionTransaction.spec.ts
- test/model/transaction/AggregateTransaction.spec.ts
- test/model/transaction/MosaicMetadataTransaction.spec.ts
- test/model/transaction/MultisigAccountModificationTransaction.spec.ts
- test/model/transaction/NamespaceMetadataTransaction.spec.ts
- test/model/transaction/SecretLockTransaction.spec.ts
- test/model/transaction/SecretProofTransaction.spec.ts
- test/model/transaction/Transaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
- Removed NamespaceName api call
- filter transaction by unresolved address
- - Fixed #760
> Filter ws transaction message by unresolved address

- e2e/e2e-preset.yml
- e2e/infrastructure/IntegrationTestHelper.ts
- e2e/infrastructure/PersistentHarvesting.spec.ts
- package-lock.json
- package.json
- src/infrastructure/TransactionHttp.ts
> Bootstrap 0.4.3 upgrade

- package-lock.json
- package.json
- src/model/node/NodeTime.ts
- src/model/transaction/Deadline.ts
- src/service/DeadlineService.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/service/DeadlineService.spec.ts
This pr fixes the unreliable unit test and puts dev up to date.
DON'T SQUASH MERGE. Commit merge would do
> Fix unit test

- package-lock.json
- package.json
- src/infrastructure/NodeHttp.ts
- src/model/node/Deployment.ts
- src/model/node/ServerInfo.ts
- src/model/node/index.ts
- test/infrastructure/NodeHttp.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
Openapi https://github.com/nemtech/symbol-openapi/pull/275
Generator: https://github.com/nemtech/symbol-openapi-generator/pull/70
fixes https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/786
> feat: added Deployment data to ServerInfo

- src/service/TransactionService.ts
- test/service/TransactionService.spec.ts
fix: deprecated flat map in Transaction Service.
> fix: announce method missing observable map

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- src/model/mosaic/MosaicInfo.ts
- src/model/transaction/MosaicDefinitionTransaction.ts
- test/model/transaction/MosaicDefinitionTransaction.spec.ts
Releasing v2.0.4
---|---|---
SDK Core| v2.0.4 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v1.0.2 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
- [Bug] Fix mosaic definition transaction from payload method.
> Releasing v2.0.4
