symbol/symbol-sdk-typescript-javascript

- e2e/infrastructure/TransactionHttp.spec.ts
- package-lock.json
- package.json
- src/model/transaction/HashType.ts
- test/model/transaction/HashTypeLengthValidator.spec.ts
- test/model/transaction/SecretLockTransaction.spec.ts
- test/model/transaction/SecretProofTransaction.spec.ts
New hash types added based on [newLockHashAlgorithm](https://github.com/nemtech/catapult-server/blob/master/plugins/txes/lock_secret/src/model/LockHashAlgorithm.h) 
Changed default secret lock hash type SHA3_512 to SHA3_256
tests added
> Issue/#57 #58 secretlock sha512 to sha256 && New lock hash algorithms for secret lock

- e2e/infrastructure/TransactionHttp.spec.ts
- package-lock.json
- package.json
- src/model/transaction/MosaicDefinitionTransaction.ts
- test/model/transaction/AggregateTransaction.spec.ts
- test/model/transaction/MosaicDefinitionTransaction.spec.ts
- Fixed MosaicDefinitionTransaction.create() to accept MosaicNonce and MosaicId
- Fixed MosaicDefinitionTransaction unit test payload with new MosaicId
> Fixed MosaicDefinitionTransaction.create() to accept MosaicNonce and MosaicId

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
Fixed fees with no default value causes web socket crash bug on account property transactions
> temp fix transaction fees issue

- package-lock.json
- package.json
- src/infrastructure/MosaicHttp.ts
- src/model/mosaic/MosaicInfo.ts
- test/model/mosaic/MosaicAmountView.spec.ts
- test/model/mosaic/MosaicInfo.spec.ts
- test/model/mosaic/MosaicView.spec.ts
Fixed MosaicInfoDTO in response of issue #76 .
https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/76
Fields updated in cow network upgrade when calling `/mosaic/{mosaicId}` endpoint, in MosaicInfoDTO: 
- Removed field `meta.active`
- Removed field `meta.index` 
- Removed field `mosaic.nonce`
- Added field `mosaic.revision`
> issue #76: Fixed MosaicInfoDTO fields with new cow DTO content

- e2e/service/MosaicService.spec.ts
- src/service/MosaicService.ts
- test/service/MosaicService.spec.ts
Fixes issue #82 : MosaicService is broken.
- `MosaicService.mosaicAmountView()` must pass single instance of `MosaicInfo` instead of `MosaicInfo[]`.
> issue #82: Fixed MosaicService to pass single MosaicInfo object instead of array

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Added `Transaction.maxFee` optional property in `create()` methods. (fixes #53)
- Added `service/AggregateTransactionService` with `isComplete()` validates cosigners (fixes #4)
- Added `model/transaction/EncryptedMessage` for encrypted message payloads
- Added `service/AggregateTransactionService` with `validateCosignatories` for completeness check (fixes #4)
- Fixed issue in `createFromDTO` with JSON format (fixes #107)
- Fixed `MosaicProperties` to make *duration*  optional (fixes #109)
> v0.11.3: more cow DTO upgrades ; several payload bugfixes

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
Fix: Error when an unlimited duration mosaic MOSAIC_DEFINITION is fetched through `accountHttp.transactions`
Reason: 
`new UInt64_1.UInt64(undefined is returned)`
Bug reproduction:
Use 
`accountHttp.transactions`
on the following account:
`AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26`
The transaction hash with an unlimited duration mosaic:
`"aggregateHash":"41AA28C4BEC707C09568AAA4C2CF432EE7F8B28E83BC8F5FE24DBF6A92A70042"`
> Bugfix: handling of unlimited duration mosaics

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
Fixed maxFee incompatibility with in-aggregate MosaicSupplyChange and in-aggregate HashLock transactions.
Upgraded to v0.11.5 and updated CHANGELOG and README.
> v0.11.5: fixed maxFee compatibility

- .travis.yml
- test/infrastructure/Listener.spec.ts
- test/service/NamespaceService.spec.ts
Fixed Issue #123 
Problem is in NamespaceService test class. The `Before All` section randomly throw exceptions. After moved the mocked service into test methods, it seems fine now. Not 100% sure how to fix it in `before()` but this fix works. Will look around see if there are better solutions.
> Fixed #123 travis log show failed

- .travis.yml
- src/model/transaction/AccountPropertyModification.ts
- src/model/transaction/AccountPropertyTransaction.ts
- src/model/transaction/ModifyAccountPropertyEntityTypeTransaction.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/model/transaction/AccountPropertyTransaction.spec.ts
Issue: #134 
- Moved filter modification creation out of `AccountPropertyTransaction`.
- Modification class is `AccountPropertyModification`
- Now support both constructor creation and static method creation.
`new AccountPropertyModification(PropertyModificationType, T)` 
or
AccountPropertyModification.createForAddress(PropertyModificationType, Address)
AccountPropertyModification.createForMosaic(PropertyModificationType, Mosaic)
AccountPropertyModification.createForEntityType(PropertyModificationType, entityType)
> Fixed #134 Account property filter modification improvement

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/CreateTransactionFromPayload.ts
- src/model/transaction/EncryptedMessage.ts
- test/core/utils/TransactionMapping.spec.ts
- test/model/transaction/EncryptedMessage.spec.ts
Bug fixed Issue: #132 
This bug was due to wrong hash algorithm (keccak256) used in shareKey derive method on encrypt / decrypt method. Now fixed.
> Fixed #132 bugs in encrypt / decrypt messages

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Removed nem2-library dependency
- Added `infrastructure/model/` with DTOs
- Added `infrastructure/api` with APIs
- Added `infrastructure/buffers` and `infrastructure/schemas`
> v0.12.2: removed nem2-library dependency

- e2e/infrastructure/NodeHttp.spec.ts
- src/infrastructure/NodeHttp.ts
- src/infrastructure/NodeRepository.ts
- src/infrastructure/infrastructure.ts
- src/model/model.ts
- src/model/node/NodeInfo.ts
- src/model/node/NodeTime.ts
- src/model/node/RoleType.ts
> Issue #164 Added NodeHttp

- src/core/format/Convert.ts
- src/core/format/Utilities.ts
- test/core/format/Convert.spec.ts
- test/core/format/IdGenerator.spec.ts
- tsconfig.json
Fixed bug on convert.utf8ToHex() by adding insignificant zero for control chars
> Issue #175 added contol char handler in convert.ts

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Elephant
- Added SignSchema to make KeyPair generation compatible with either of Catapult and NIS.
- Added SignSchema with KECCAK_REVERSED_KEY and SHA3. The SDK by default uses SHA3 which is the Catapult signature schema.
- Fixed transaction versions back to version 1
- Added `signTransactionGivenSignatures` to cope with off chain aggregated complete transaction co signing.
> v0.13.0: base compatibility for Elephant protocol upgrade

- src/infrastructure/AccountHttp.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/ChainHttp.ts
- src/infrastructure/DiagnosticHttp.ts
- src/infrastructure/Http.ts
- src/infrastructure/MosaicHttp.ts
- src/infrastructure/NamespaceHttp.ts
- src/infrastructure/NetworkHttp.ts
- src/infrastructure/NodeHttp.ts
- src/infrastructure/TransactionHttp.ts
- src/infrastructure/api/accountRoutesApi.ts
- src/infrastructure/api/blockRoutesApi.ts
- src/infrastructure/api/chainRoutesApi.ts
- src/infrastructure/api/diagnosticRoutesApi.ts
- src/infrastructure/api/mosaicRoutesApi.ts
- src/infrastructure/api/namespaceRoutesApi.ts
- src/infrastructure/api/networkRoutesApi.ts
- src/infrastructure/api/nodeRoutesApi.ts
- src/infrastructure/api/transactionRoutesApi.ts
- src/infrastructure/templates/api-single.mustache
- test/infrastructure/TransactionHttp.spec.ts
Reverts nemtech/nem2-sdk-typescript-javascript#201
Bugs with CLI after merge :
```
src/commands/account/generate.ts:128:22 - error TS2345: Argument of type 'Observable<NetworkType>' is not assignable to parameter of type 'ObservableInput<NetworkType>'.
Type 'Observable<NetworkType>' is not assignable to type 'Subscribable<NetworkType>'.
Types of property 'subscribe' are incompatible.
Type '{ (observer?: NextObserver<NetworkType> | ErrorObserver<NetworkType> | CompletionObserver<NetworkType> | undefined): Subscription; (next?: ((value: NetworkType) => void) | undefined, error?: ((error: any) => void) | undefined, complete?: (() => void) | undefined): Subscription; }' is not assignable to type '{ (observer?: NextObserver<NetworkType> | ErrorObserver<NetworkType> | …
```
> Revert "Fixed compatibility issue on new rxjs version"

- src/infrastructure/MosaicHttp.ts
Fix return wrong duration value in `getMosaic`
> fix return wrong duration value

- README.md
- e2e/infrastructure/TransactionHttp.spec.ts
- e2e/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- e2e/infrastructure/transaction/ValidateTransaction.ts
- src/infrastructure/AccountHttp.ts
- src/infrastructure/model/models.ts
- src/infrastructure/model/mosaicDTO.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/model/transaction/MosaicDefinitionTransaction.ts
- src/model/transaction/MosaicGlobalRestrictionTransaction.ts
- src/model/transaction/NamespaceRegistrationTransaction.ts
- src/model/wallet/EncryptedPrivateKey.ts
- src/model/wallet/SimpleWallet.ts
- test/core/utils/TransactionMapping.spec.ts
- test/model/mosaic/Mosaic.spec.ts
- test/model/mosaic/MosaicFlags.spec.ts
- Unused mosaicProperties code removed
- Integration test fixed
- jsdoc fixed
- Renamed `NamespaceType` to  `RegistrationType` (missed in E3 schema patch)
- Fixed EncryptedPrivateKey cannot be instantiate issue
> JAV-19 [Github #259 #260 #241] Various small issues fixed

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Elephant.3 / Fuschicho
- Added `Metadata` rest api endpoints and DTOs
- Added `MosaicRestriction` rest api endpoints and DTOs
- Added `MetadataTransactionService` which eases the meta data transaction creation without knowing previous meta data values
- Added `MosaicRestrictionTransactionService` which eases the mosaic restriction transaction creation without knowing previous restriction details.
- Changed `MetadataTransaction` and `Metadata state` value to use raw string (utf8 encoding).
- Fixed  `Namespace/Names` endpoint issue
- Fixed `Mosaic` endpoint issue
- Improved unit and e2e tests
> v0.13.4 pre-rc release

- src/core/format/KeyGenerator.ts
- src/core/format/index.ts
- test/core/format/KeyGenerator.spec.ts
PR adds `core/format/KeyGenerator`. Usage:
`const u64 = KeyGenerator.fromString('key_name') // returns UInt64`
> Implement KeyGenerator

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fuschicho
- Added `KeyGenerator` class for generating UInt64 Keys from string.
- Fixed `MosaicAmountView` issue. Now return observable of array.
- Optimised `Account restriction` endpoints by returning simple payload.
- Fixed http repository `error handling` issues.
- Fixed bugs in `Alias` interface.
- Fixed `MosaicId significant byte` not detected properly in TransactionPayload.
- Fixed only `MIJIN_TEST` network type allowed in NetworkTypeHttp.
- Applied latest OpenAPI doc (`v0.7.19`).
- Changed `SignedTransaction` class constructor to public.
- Changed `MosaicRestrictionKey` format to be Hexadecimal.
- Other small fixes.
> v0.14.0 Release

- src/model/message/PersistentHarvestingDelegationMessage.ts
- src/model/transaction/PersistentDelegationRequestTransaction.ts
- test/model/message/PersistentHarvestingDelegationMessage.spec.ts
- test/model/transaction/PersistentDelegationRequestTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
- Fixed bug in PersistentDelegationRequestTransaction.
Issue: #300
> JAV-67 Fixed PersistentDelegationRequestTransaction

- src/model/transaction/AggregateTransaction.ts
- src/model/transaction/InnerTransaction.ts
- src/model/transaction/Transaction.ts
- src/service/AggregateTransactionService.ts
- test/model/transaction/AggregateTransaction.spec.ts
- Changed signer param to be optional on `toAggregate` when adding inner transactions. If not signer in inner transaction not provided, the main Aggregate transaction signer will be delegated.
- This change **ONLY** applies on **AggregateComplete** transaction
- Added validation if no signer (inner tx) provided in AggregateBond transaction
- Added tests
> JAV-38  Inner transaction singer delegation

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Added `Receipt serializer & hash generator` for auditing receipt merkle proof.
- Added `Unresolved (NamespaceId)` support on `MosaicRestriction` and `MosaicMetadata` transactions.
- Fixed `Mosaic array ordering` in `TransferTransaction`.
- Fixed issues in `PersistentDelegationRequestTransaction`.
- Other small fixes from community feedbacks.
> v0.14.1 Release

- src/core/utils/UnresolvedMapping.ts
- test/model/transaction/TransferTransaction.spec.ts
Fixed address alias deserialization bug as NamespaceId bytes need to be reversed.
issue: #307
> JAV-69 Fixed address alias deserialization bug

- e2e/infrastructure/TransactionHttp.spec.ts
- e2e/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- e2e/infrastructure/transaction/ValidateTransaction.ts
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/transaction/MosaicSupplyChangeTransaction.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/model/transaction/MosaicSupplyChangeTransaction.spec.ts
- Fixed MosaicSupplyChangeTransaction still uses old schema field `Direction` issue. Replaced to `Action`
Issue: #309
> Fixed MosaicSupplyChangeTransaction schema issue (Direction -> Action)

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- Fixed `MetadataTransactionSercie` value delta issue.
- Fixed `Convert.xor()` method issue.
> v0.14.3 Release

- src/infrastructure/Listener.ts
- src/model/transaction/TransactionStatusError.ts
- test/infrastructure/Listener.spec.ts
- test/model/transaction/TransactionStatusError.spec.ts
Hi @rg911 
I've added the filter by address to the listener's status subscription, 
https://github.com/nemtech/catapult-rest/pull/174 fix has been merged. Remember to get the latest catapult-rest when working as the new status listener requires the latest rest.
> TS-77 filtering listener's status message by subscribed address.

- .gitignore
- src/core/format/RawAddress.ts
- src/model/account/Address.ts
- test/core/format/RawAddress.spec.ts
- test/model/account/Address.spec.ts
Hi @rg911 
I've revisited the is valid address methods. The solution is that RawAddress class handles the low-level byte array validation doing the hashes and checksum checks. The Address class handles the high-level validation, with 2 methods isValidPlainAddress and isValidEncodedAddress that receive strings. The address delegates the validation to RawAddress. I've also added Address.encoded() so you can get the hex string version of the address. 
Have a look at let me know what do you think.
> TS-81 Address.isValidAddress methods

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.1
- Added `Address.isValidAddress` for plain address string validation.
- Added `Address filter` in transaction status websocket listener channel.
- Changed `MetadataTransactionService` return type from `Transaction` to `Union types`.
- Made `decodeHex` method and `EmptyAlias` class public.
- Fixed const network type used in `AliasToRecipient` method.
- Fixed `SecretLock` and `SecretProof` transaction not using `UnresolvedAddress` issue.
- Fixed `Size` method issues for transactions.
- Fixed other JSDoc issues.
> v0.14.4 release

- src/model/transaction/AggregateTransaction.ts
- test/model/transaction/AggregateTransaction.spec.ts
- Added `AggregateTransaction.addCosignatures` method
- Added unit test to fill cosignatures after object creation
> #345: add method addCosignatures to fill cosignatures offline

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.2
- Added `networkType` as an optional paramter in `Http` abstract to recude the number of requests to the catapult-rest server
- Added `resolveAlias` in transaction for resolving `UnresolvedAddress` and `UnresolvedMosaic` inside a transaction.
- Added `TransactionService` class.
- Added `resolveAlias` service in `TransactionService` which resolves alias(es) in transaction(s) from block `ResolutionStatement`.
- Consolicated transaction announcement and websocket `confirmed` listener into one service call in `TransactionService`.
- Consolidated `AggregateBonded` tranaction announcement (aggregateBonded + lockFund) into one service call in `TransactionService`.
> v0.15.1 release

- src/infrastructure/AccountHttp.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/RestrictionMosaicHttp.ts
- src/infrastructure/TransactionHttp.ts
Hi @rg911 
This PR fixes https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/367 / https://nem.atlassian.net/browse/TS-111
Have a look when you have time.
> Fixed Github 367 - TS-111

- .travis.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- test/model/transaction/TransferTransaction.spec.ts
- tsconfig.json
**Milestone**: Fushicho.3
- Added epochAdjustment introduced in catapult-server v0.9.1.1 (Fushicho.3)
- Added `setMaxFee` to `Transaction` which calculate max transaction fee using `feeMultiplier * transaction.size`.
- Optimised `resolveAlias` implementation in transaction using object spread operator.
- Fixed couple of bugs in `blockHttp` and unit tests
- Fixed travis-CI issue
- Fixed `coveralls` always return 100% issue
> v0.16.0 release

- package-lock.json
- package.json
- src/service/MosaicRestrictionTransactionService.ts
- test/service/MosaicRestrictionTransactionservice.spec.ts
Allow MosaicRestrictionTransactionService to use referenceMosaicId alias
Upgraded mockito
Fixed handlebars security issue
> Changed MosaicRestrictionTransactionService to use repositories

- src/model/UInt64.ts
- test/model/UInt64.spec.ts
Added Operation
- `Add()`
- `Subtract()` 
Fixed #376
> UInt64 operation

- src/core/utils/DtoMapping.ts
- src/model/transaction/AccountAddressRestrictionTransaction.ts
- src/model/transaction/AccountMosaicRestrictionTransaction.ts
- src/model/transaction/AggregateTransaction.ts
- src/model/transaction/LockFundsTransaction.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/model/transaction/MosaicGlobalRestrictionTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/MosaicSupplyChangeTransaction.ts
- src/model/transaction/SecretLockTransaction.ts
- src/model/transaction/SecretProofTransaction.ts
- src/model/transaction/Transaction.ts
- src/model/transaction/TransferTransaction.ts
- test/infrastructure/RepositoryFactory.spec.ts
- test/model/transaction/AccountLinkTransaction.spec.ts
- test/model/transaction/AccountMetadataTransaction.spec.ts
- test/model/transaction/AggregateTransaction.spec.ts
- test/model/transaction/LockFundsTransaction.spec.ts
- test/model/transaction/MosaicAddressRestrictionTransaction.spec.ts
- test/model/transaction/MosaicAliasTransaction.spec.ts
- test/model/transaction/MosaicDefinitionTransaction.spec.ts
- test/model/transaction/MosaicGlobalRestrictionTransaction.spec.ts
- test/model/transaction/MosaicMetadataTransaction.spec.ts
- test/model/transaction/MosaicSupplyChangeTransaction.spec.ts
- test/model/transaction/MultisigAccountModificationTransaction.spec.ts
- test/model/transaction/NamespaceMetadataTransaction.spec.ts
- test/model/transaction/NamespaceRegistrationTransaction.spec.ts
- test/model/transaction/SecretLockTransaction.spec.ts
- test/model/transaction/SecretProofTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
> Fixed #390 Spread operator does not assign super class methods

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.3
- Added basic `operations for UInt64` (Add(), Substract()).
- Added `RepositoryFactoryHttp ` which creates concrete http classes in a factory patten.
- Added `NetworkType` and `GenerationHash` cache for all Http repositories which reduces the number of rest calls.
- Added static mathod to create `SimpleWallet` from rest DTO payload.
- Added `TransactionType filter` in `AccountHttp` which can be used for filtering account transactions by type.
- Added `IntegrationTestHelper` which optimised e2e / integration tests by automatically tracking the changes from catapult rest. Also support loading test accounts directly from catapult-bootstrap-server generated nemesis addresses.
- Replaced `Records limitation steps (25,50,75,100)` with just number input.
- Fixed …
> v0.16.1 release

- e2e/infrastructure/BlockHttp.spec.ts
- e2e/infrastructure/IntegrationTestHelper.ts
- e2e/infrastructure/Listener.spec.ts
- src/infrastructure/Listener.ts
- src/model/account/MultisigAccountGraphInfo.ts
- src/model/transaction/TransactionStatusError.ts
- test/infrastructure/Listener.spec.ts
- test/model/transaction/TransactionStatusError.spec.ts
Fixed #411 #410 
- Fixed transaction status issue due to `Status` has been renamed to `code` in `Catapult-rest`.
- Fixed a blockHttp integration test time out bug
- Removed internal from MultisigAccountGraphInfo
> Fixed listener status bug and make MultisigAccountGraphInfo constructor public

- e2e/service/MosaicRestrictionTransactionService.spec.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/service/MosaicRestrictionTransactionService.ts
- test/service/MosaicRestrictionTransactionservice.spec.ts
- Allow unresolved in mosaic restriction
- Fixed restrictionKey format bug due to `restrictionKey` changed from `hex` to `numericString`
Fixed #403
> Allow unresolved in mosaic restriction transaction

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.3
---|---|---
SDK Core| v0.16.2 | https://www.npmjs.com/package/nem2-sdk 
Catbuffer Library| v0.0.7 | https://www.npmjs.com/package/catbuffer 
Client Library | v0.7.20-alpha.6  | https://www.npmjs.com/package/nem2-sdk-openapi-typescript-node-client 
- Refactored to replace generated codes by public library package for both `Catbuffer` and `OpenAPI Http Client`.
- Added unresolved (mosaicId, address) support in `MosaicRestrictionTransaction`.
- Added `toHex()` in `MosaicNonce` class.
- Exposed `MultisigAccountGraphInfo` class constructor to public.
- Fixed `transaction status` issue in both `Http` and `Websocket` due to schema update.
> v0.16.2 release

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.3
---|---|---
SDK Core| v0.16.3 | https://www.npmjs.com/package/nem2-sdk
Catbuffer Library| v0.0.7 | https://www.npmjs.com/package/catbuffer
Client Library | v0.7.20-beta.6  | https://www.npmjs.com/package/nem2-sdk-openapi-typescript-node-client
- Fixed http client (OpenAPI client package) does not support ES6 issue.
> v0.16.3 release

- e2e/infrastructure/TransactionHttp.spec.ts
- e2e/service/MetadataTransactionService.spec.ts
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/CreateTransactionFromPayload.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/transaction/AccountAddressRestrictionTransaction.ts
- src/model/transaction/AccountLinkTransaction.ts
- src/model/transaction/AccountMetadataTransaction.ts
- src/model/transaction/AccountMosaicRestrictionTransaction.ts
- src/model/transaction/AccountOperationRestrictionTransaction.ts
- src/model/transaction/LockFundsTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/MultisigAccountModificationTransaction.ts
- src/model/transaction/NamespaceMetadataTransaction.ts
- src/model/transaction/NamespaceRegistrationTransaction.ts
- src/model/transaction/TransactionType.ts
- src/model/transaction/TransactionVersion.ts
- src/service/AggregateTransactionService.ts
- src/service/TransactionService.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/infrastructure/transaction/ValidateTransaction.ts
- test/model/transaction/TransactionType.spec.ts
- test/service/MetadataTransactionservice.spec.ts
Renamed TransactionType and TransactionVersion enum names to match Catapult doc
Fixed #428
> Fixed #428 Transaction type & version enum name match

- e2e/infrastructure/BlockHttp.spec.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/BlockRepository.ts
- src/infrastructure/ReceiptHttp.ts
- src/infrastructure/ReceiptRepository.ts
- src/infrastructure/RepositoryFactoryHttp.ts
- src/service/TransactionService.ts
- test/infrastructure/RepositoryFactory.spec.ts
- Updated block & receipt http to use UInt64 height
Fixed #429
> UInt64 Height in Block and Receipt Http

- e2e/infrastructure/Listener.spec.ts
- e2e/infrastructure/TransactionHttp.spec.ts
- src/core/utils/TransactionMapping.ts
- src/infrastructure/Listener.ts
- src/infrastructure/transaction/CreateTransactionFromPayload.ts
- src/model/transaction/AccountAddressRestrictionTransaction.ts
- src/model/transaction/AccountLinkTransaction.ts
- src/model/transaction/AccountMetadataTransaction.ts
- src/model/transaction/AccountMosaicRestrictionTransaction.ts
- src/model/transaction/AccountOperationRestrictionTransaction.ts
- src/model/transaction/AggregateTransaction.ts
- src/model/transaction/LockFundsTransaction.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/model/transaction/MosaicAliasTransaction.ts
- src/model/transaction/MosaicGlobalRestrictionTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/MosaicSupplyChangeTransaction.ts
- src/model/transaction/MultisigAccountModificationTransaction.ts
- src/model/transaction/NamespaceMetadataTransaction.ts
- src/model/transaction/SecretProofTransaction.ts
- src/model/transaction/TransferTransaction.ts
- test/model/transaction/AggregateTransaction.spec.ts
> Fixed lint issues

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.4(RC3)
---|---|---
SDK Core| v0.16.4 | https://www.npmjs.com/package/nem2-sdk
Catbuffer Library| v0.0.11 | https://www.npmjs.com/package/catbuffer
Client Library | v0.7.20-beta.7  | https://www.npmjs.com/package/nem2-sdk-openapi-typescript-node-client
- Core 0.9.2.1 compatible. Changed hash algorithm for shared key derivation to `HKDF-HMAC-Sha256`.
- Removed `senderPrivateKey` in `Persistent Delegation Request Transaction`. Instead, it uses an `ephemeral key pair` and the `EphemeralPublicKey` is now attached in the `PersistentDelegationMessage` payload.
- Removed `salt` encryption and decryption functions which uses `HKDF-HMAC-Sha256` instead. This only affects the encrypted payload.
- Added missing export in `Infrastructure` classes / interfaces.
- …
> v0.16.4 Release

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.4(RC3)
---|---|---
SDK Core| v0.16.5 | https://www.npmjs.com/package/nem2-sdk
Catbuffer Library| v0.0.11 | https://www.npmjs.com/package/catbuffer
Client Library | v0.7.20-beta.7  | https://www.npmjs.com/package/nem2-sdk-openapi-typescript-node-client
- Fixed circular reference issue after removed `InnerTransaction` class.
> v0.16.5 release

- e2e/infrastructure/AccountHttp.spec.ts
- e2e/infrastructure/BlockHttp.spec.ts
- e2e/infrastructure/ChainHttp.spec.ts
- e2e/infrastructure/DiagnosticHttp.spec.ts
- e2e/infrastructure/IntegrationTestHelper.ts
- e2e/infrastructure/Listener.spec.ts
- e2e/infrastructure/MetadataHttp.spec.ts
- e2e/infrastructure/MosaicHttp.spec.ts
- e2e/infrastructure/NamespaceHttp.spec.ts
- e2e/infrastructure/NetworkHttp.spec.ts
- e2e/infrastructure/NodeHttp.spec.ts
- e2e/infrastructure/RestrictionHttp.spec.ts
- e2e/infrastructure/TransactionHttp.spec.ts
- e2e/infrastructure/UnresolvedMapping.spec.ts
- e2e/service/MetadataTransactionService.spec.ts
- e2e/service/MosaicRestrictionTransactionService.spec.ts
- e2e/service/MosaicService.spec.ts
- e2e/service/TransactionService.spec.ts
- e2e/service/TransactionService_AggregateBonded.spec.ts
E2E test improvements by replacing done callbacks with async/await/promises when possible.
> E2E test code improvements

- e2e/infrastructure/NetworkHttp.spec.ts
- package-lock.json
- package.json
- src/infrastructure/NetworkHttp.ts
- src/infrastructure/NetworkRepository.ts
- src/model/blockchain/NetworkFees.ts
- src/model/blockchain/NetworkName.ts
- Applied openAPI 0.8.3
- Added NetworkFees
Fixed #443
> Applied openAPI 0.8.3

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/service/service.ts
**Milestone**: Fushicho.4(RC3 0.9.3.1)
---|---|---
SDK Core| v0.17.0 | https://www.npmjs.com/package/nem2-sdk
Catbuffer Library| v0.0.11 | https://www.npmjs.com/package/catbuffer
Client Library | v0.8.4  | https://www.npmjs.com/package/nem2-sdk-openapi-typescript-node-client
- **[BREAKING CHANGE]** Changed hashing algorithm to cope catapult-server changes. All Key derivation and signing are now using `SHA512`. Removed `SignSchema` so `NetworkType` is no longer bonded to the schema anymore (sha3 / keccak). This change will affect all existing keypairs / address (derived from public key) and  transaction signatures.
- **[BREAKING CHANGE]** Added new `TransactionFilter` parameter to `AccountHttp` which is now support filtering with list of transaction type.
- Added …
> v0.17.0 release

- e2e/infrastructure/AccountHttp.spec.ts
- e2e/infrastructure/BlockHttp.spec.ts
- src/infrastructure/Http.ts
- src/infrastructure/QueryParams.ts
- src/infrastructure/TransactionFilter.ts
- test/infrastructure/TransactionFilter.spec.ts
> Query params arguments in constructor, fixes #456

- e2e/infrastructure/BlockHttp.spec.ts
- src/infrastructure/BlockHttp.ts
- src/model/blockchain/BlockInfo.ts
- test/model/blockchain/BlockInfo.spec.ts
- Added numStatements
Fixed #464
> Added numStatements

- src/core/crypto/nacl_catapult.ts
- src/model/transaction/Transaction.ts
- test/model/transaction/Transaction.spec.ts
- Added s-part in transaction hash
Fixed #470
> Added s-part in transaction hash

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.4(RC3 0.9.3.1)
---|---|---
SDK Core| v0.17.2 | https://www.npmjs.com/package/symbol-sdk
Catbuffer | v0.0.11 | https://www.npmjs.com/package/catbuffer-typescript
Client Library | v0.8.5  | https://www.npmjs.com/package/symbol-openapi-typescript-node-client
- **[BREAKING CHANGE]** Added `s-part` of transaction signature to transaction hash.
- Added `numStatements` to `blockInfo` model.
- Fixed `mosaicNonce` issue in `createTransactionFromPayload`.
- Improved error handling in WS `listener` and `TransactionService`.
- Improved test coverage.
> 0.17.2 release

- src/infrastructure/NodeHttp.ts
- src/model/node/NodeTime.ts
- test/infrastructure/NodeHttp.spec.ts
- Updated nodetime model using UInt64
Fixed #472
> Updated nodetime model using UInt64

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Fushicho.4(RC3 0.9.3.1)
---|---|---
SDK Core| v0.17.3 | https://www.npmjs.com/package/symbol-sdk
Catbuffer | v0.0.11 | https://www.npmjs.com/package/catbuffer-typescript
Client Library | v0.8.5  | https://www.npmjs.com/package/symbol-openapi-typescript-node-client
- Fixed `MosaicNonce` issue handling signed integer from rest payload.
- **[BREAKING CHANGE]** Updated `NodeTime` model to use `UInt64`.
> v0.17.3 release

- .travis.yml
- package-lock.json
- package.json
- src/infrastructure/AccountHttp.ts
- src/infrastructure/Http.ts
- test/infrastructure/AccountHttp.spec.ts
- test/infrastructure/NodeHttp.spec.ts
- travis/uploadArchives.sh
Addresses issue https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/458. Please read the reason for this PR there.
Once this PR is merged, Travis will start deploying an alpha version to npm every master build (nodejs version 8 builder).
The notation is
`symbol-sdk:$version-alpha-$datetime`
For example
`symbol-sdk:0.17.2-alpha-202002251427` (tag alpha) 
Note that the alpha version uses the next release version, right now it would be `0.17.2-alpha-xxxx`. Once `0.17.2` is released, the next alpha version would be `0.17.3-alpha-xxxx`
I couldn't find any --pre option in 
https://docs.npmjs.com/cli/publish
Also, the --tag doesn't allow redeploy if the version is the same. The travis script generates a new alpha version when executed
Note: `NPM_TOKEN` needs to be provided in …
> NPM Alpha deployments from master

- src/model/transaction/Transaction.ts
> Make `getSigningBytes` public

- src/infrastructure/MosaicHttp.ts
- test/infrastructure/MosaicHttp.spec.ts
- test/service/MosaicService.spec.ts
> Refactored MosaicService unit test

- CHANGELOG.md
- README.md
**Milestone**: Fushicho.4(RC3 0.9.3.2)
---|---|---
SDK Core| v0.17.4 | https://www.npmjs.com/package/symbol-sdk
Catbuffer | v0.0.11 | https://www.npmjs.com/package/catbuffer-typescript
Client Library | v0.8.9  | https://www.npmjs.com/package/symbol-openapi-typescript-node-client
- Added `SimpleWallet.toDTO()` method which returns JSON serialized object.
- Applied latest Symbol OpenAPI generated code (`v0.8.9`).
- Added automated release scripts for Travis.
- Added multiple version spport for TS-Doc.
- Optimised unit tests and improved test coverage.
- Changed internal method `getSigningByte` to public.
- Removed constant of namespace `MaxDepth (default: 3)` which can be retrieved from network properties endpoint.
- Fixed Github security alert on `minimist` …
> v0.17.4 release

- src/core/format/RawUInt64.ts
- src/model/UInt64.ts
- test/model/UInt64.spec.ts
- Added type on unit64Raw.compact
- Throw exception if cannot compact to number
Fixed #507
> Throw exception on UInt64.compact.

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Gorilla.1(0.9.5.1)
---|---|---
SDK Core| v0.19.0 | https://www.npmjs.com/package/symbol-sdk
Catbuffer | v0.0.18 | https://www.npmjs.com/package/catbuffer-typescript
Client Library | v0.8.10  | https://www.npmjs.com/package/symbol-openapi-typescript-node-client
- **[BREAKING CHANGE]** `Transaction signing` is now using `GenerationHashSeed` from `NodeInfo` or `NetworkProperties`. GenerationHash on Nemesis block (block:1) is `NOT` used for signing purposes.
- **[BREAKING CHANGE]** Renamed `AccountLinkTransaction` to `AccountKeyLinkTransaction`.
- **[BREAKING CHANGE]** Renamed `networkGenerationHash` to `networkGenerationHashSeed` in `NodeInfo`.
- **[BREAKING CHANGE]** replaced `linkedPublickKey` with `supplementalAccountKeys` array in `AccountInfo`. …
> 0.19.0 release

- src/model/transaction/AccountAddressRestrictionTransaction.ts
- src/model/transaction/AccountKeyLinkTransaction.ts
- src/model/transaction/AccountMetadataTransaction.ts
- src/model/transaction/AccountMosaicRestrictionTransaction.ts
- src/model/transaction/AccountOperationRestrictionTransaction.ts
- src/model/transaction/AccountRestrictionTransaction.ts
- src/model/transaction/AddressAliasTransaction.ts
- src/model/transaction/AggregateTransaction.ts
- src/model/transaction/AliasTransaction.ts
- src/model/transaction/LockFundsTransaction.ts
- src/model/transaction/MosaicAddressRestrictionTransaction.ts
- src/model/transaction/MosaicAliasTransaction.ts
- src/model/transaction/MosaicDefinitionTransaction.ts
- src/model/transaction/MosaicGlobalRestrictionTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/MosaicSupplyChangeTransaction.ts
- src/model/transaction/MultisigAccountModificationTransaction.ts
- src/model/transaction/NamespaceMetadataTransaction.ts
- src/model/transaction/NamespaceRegistrationTransaction.ts
- src/model/transaction/NodeKeyLinkTransaction.ts
- src/model/transaction/PersistentDelegationRequestTransaction.ts
- src/model/transaction/SecretLockTransaction.ts
- src/model/transaction/SecretProofTransaction.ts
- src/model/transaction/TransferTransaction.ts
- src/model/transaction/VotingKeyLinkTransaction.ts
- src/model/transaction/VrfKeyLinkTransaction.ts
- test/core/utils/TransactionMappingWithSignatures.spec.ts
When calling `Transaction.serialize()` which does not serialize signer and signature even both are not undefined. 
- Added signature and signer to `Transaction.create...` and `Transaction.serialize`
- Added signature and signer to loadFromPayload.
Fixed #571
> Added signature and signer to loadFromPayload

- CHANGELOG.md
- README.md
- src/infrastructure/infrastructure.ts
**Milestone**: Gorilla.1(0.9.5.1)
---|---|---
SDK Core| v0.19.2 | https://www.npmjs.com/package/symbol-sdk
Catbuffer | v0.0.19 | https://www.npmjs.com/package/catbuffer-typescript
Client Library | v0.8.11  | https://www.npmjs.com/package/symbol-openapi-typescript-node-client
- **[BREAKING CHANGE]** Replaced constructor parameter `config` with `url` in `Listener` class. The constructor is now **only using a complete websocket url (e.g. http://localhost:3000/ws or ws://localhost:3000/ws) but not rest-gateway url anymore (It will NOT append `/ws` suffix to the input url)**.
- **[BREAKING CHANGE]** `RepositoryFactory`: Optional constructor parameters has been moved into `RepositoryFactoryConfig` interface (optional).
- **[BREAKING CHANGE]** Added `websocketInjected` …
> v0.19.2 release change notes

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
**Milestone**: Gorilla.1(0.9.6.1)
---|---|---
SDK Core| v0.20.0 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v0.0.20 | [catbuffer-typescript](]-typescript)
Client Library | v0.9.2  | [symbol-openapi-typescript-node-client](https://www.npmjs.com/package/symbol-openapi-typescript-node-client)
- **[BREAKING CHANGE]** Model property name changes:
1. **MetadataEntry**: senderPublicKey: string => sourceAddress: Address; targetPublicKey: string => targetAddress: Address
2. **MultisigAccountGraphInfo**: multisigAccounts => multisigEntries
3. **MultisigAccountInfo**: account: PublicAccount => accountAddress: Address; cosignatories: PublicAccount[] => cosignatoryAddresses: Address; multisigAccounts: PublicAccount[] => multisigAddresses: Address[] …
> 9.6.1 release

- src/core/utils/DtoMapping.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/Listener.ts
- src/infrastructure/MosaicHttp.ts
- src/infrastructure/QueryParams.ts
- src/infrastructure/ReceiptHttp.ts
- src/infrastructure/TransactionHttp.ts
- src/infrastructure/infrastructure.ts
- src/infrastructure/searchCriteria/BlockOrderBy.ts
- src/infrastructure/searchCriteria/BlockSearchCriteria.ts
- src/infrastructure/searchCriteria/Order.ts
- src/infrastructure/searchCriteria/SearchCriteria.ts
- src/model/blockchain/MerklePosition.ts
- src/model/model.ts
- src/service/BlockService.ts
- test/core/utils/EnumMapping.spec.ts
- test/infrastructure/AccountHttp.spec.ts
- test/infrastructure/BlockHttp.spec.ts
- test/infrastructure/MetadataHttp.spec.ts
- test/infrastructure/QueryParams.spec.ts
- test/infrastructure/SearchCriteria.spec.ts
- test/infrastructure/TransactionSearchCriteria.spec.ts
- test/service/BlockService.spec.ts
- Added enumMapper
- Added wrapper enums for Order, BlockOrderBy and MeklePosition
Fixed #608
> OpenAPI Enum type mapper

- CHANGELOG.md
- README.md
**Milestone**: Gorilla.1(0.9.6.2)
---|---|---
SDK Core| v0.20.3 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v0.0.21 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
Client Library | v0.9.3  | [symbol-openapi-typescript-fetch-client](https://www.npmjs.com/package/symbol-openapi-typescript-fetch-client)
- **[BREAKING CHANGE]** Added `startPoint` and `endPoint` in `VotingKeyLinkTransaction`.
- **[BREAKING CHANGE]** Renamed `SupplementalAccountKeys` to `SupplementalPublicKeys`. The new `SupplementalPublicKeys` has been changed from `array` type to an `object` containing: `linked`, `node`, `vrf` and `voting` key(s).
- **[BREAKING CHANGE]** Changed to use the SDK's own enums for `order`, `orderBy`, `blockOrderBy` …
> 0.20.3 release

- CHANGELOG.md
- README.md
**Milestone**: Gorilla.1(0.9.6.2)
---|---|---
SDK Core| v0.20.5 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v0.0.21 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
Client Library | v0.9.4  | [symbol-openapi-typescript-fetch-client](https://www.npmjs.com/package/symbol-openapi-typescript-fetch-client)
- Added `maxVotingKeysPerAccount`, `minVotingKeyLifetime` and `maxVotingKeyLifetime` in **ChainProperties**.
- Updated fetch client version to `0.9.4`.
> 0.20.5 release

- CHANGELOG.md
- README.md
**Milestone**: Gorilla.1(0.9.6.2)
---|---|---
SDK Core| v0.20.6 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v0.0.21 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
Client Library | v0.9.4  | [symbol-openapi-typescript-fetch-client](https://www.npmjs.com/package/symbol-openapi-typescript-fetch-client)
- Changed to use default fetchAPI (`node-fetch`) in repository construction (not relying on repository factory builders).
> 0.20.6 release

- e2e/infrastructure/AccountHttp.spec.ts
- e2e/infrastructure/NamespaceHttp.spec.ts
- e2e/service/AccountService.spec.ts
- package-lock.json
- package.json
- src/infrastructure/AccountHttp.ts
- src/infrastructure/AccountRepository.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/NamespaceHttp.ts
- src/infrastructure/NamespaceRepository.ts
- src/infrastructure/paginationStreamer/AccountPaginationStreamer.ts
- src/infrastructure/paginationStreamer/NamespacePaginationStreamer.ts
- src/infrastructure/searchCriteria/AccountOrderBy.ts
- src/infrastructure/searchCriteria/AccountSearchCriteria.ts
- src/infrastructure/searchCriteria/NamespaceSearchCriteria.ts
- src/service/AccountService.ts
- src/service/NamespaceService.ts
- src/service/interfaces/IAccountService.ts
- test/core/utils/EnumMapping.spec.ts
- test/infrastructure/AccountHttp.spec.ts
- test/infrastructure/NamespaceHttp.spec.ts
- test/infrastructure/streamer/AccountPaginationStreamer.spec.ts
- test/infrastructure/streamer/NamespacePaginationStreamer.spec.ts
- test/service/AccountService.spec.ts
- test/service/NamespaceService.spec.ts
Implemented account and namespace pagination
Fixed #627
> Account & Namespace pagination

- src/core/format/Convert.ts
- src/model/message/Message.ts
- test/core/format/Convert.spec.ts
- test/model/message/Message.spec.ts
for supporting emoji in message.
> change message Encoding/Decoding method

- src/model/transaction/CosignatureTransaction.ts
- test/model/transaction/CosignatureTransaction.spec.ts
> Added optional param in CosignatureTransaction.signWith

- src/infrastructure/searchCriteria/TransactionSearchCriteria.ts
Fixed doc for issue https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/633
> Fixed transaction group search doc

- e2e/infrastructure/ReceiptHttp.spec.ts
- package-lock.json
- package.json
- src/infrastructure/ReceiptHttp.ts
- src/infrastructure/searchCriteria/TransactionStatementSearchCriteria.ts
Allowing transactions statement filtering by multiple recipients types
> Statement recipient types filtering

- src/core/crypto/Crypto.ts
- src/model/transaction/TransferTransaction.ts
- test/core/crypto/crypto.spec.ts
- test/model/message/PersistentHarvestingDelegationMessage.spec.ts
- test/model/transaction/PersistentDelegationRequestTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
To adopt security reviews and recent catapult-server changes, the message (including persistent harvesting) encryption/decryption algorithm has been updated from AES-CBC to AES-GCM.
> Encode transaction message using AES-GCM

- e2e/infrastructure/MetadataHttp.spec.ts
- src/model/message/MessageMarker.ts
- src/model/message/PersistentHarvestingDelegationMessage.ts
- src/model/transaction/PersistentDelegationRequestTransaction.ts
- src/model/transaction/TransferTransaction.ts
- test/model/message/PersistentHarvestingDelegationMessage.spec.ts
- test/model/transaction/PersistentDelegationRequestTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
- Updated delegated harvesting message marker to `E201735761802AFE`
- Added vrf private key to the message payload, so the encrypted message payload becomes `signingPrivateKey + vrfPrivateKey`
Fixed  - #147
> Updated delegated harvesting message payload.

- src/infrastructure/Listener.ts
- src/model/transaction/Deadline.ts
- test/infrastructure/Listener.spec.ts
> Added ws message wrapper based on rest changes

- package-lock.json
- package.json
- src/infrastructure/Http.ts
- src/infrastructure/Page.ts
- test/infrastructure/AccountHttp.spec.ts
- test/infrastructure/BlockHttp.spec.ts
- test/infrastructure/MetadataHttp.spec.ts
- test/infrastructure/MosaicHttp.spec.ts
- test/infrastructure/NamespaceHttp.spec.ts
- test/infrastructure/Page.spec.ts
- test/infrastructure/ReceiptHttp.spec.ts
- test/infrastructure/TransactionHttp.spec.ts
- test/infrastructure/streamer/PaginationStreamerTestHelper.ts
- test/service/AccountService.spec.ts
- test/service/MetadataTransactionservice.spec.ts
> Removed totalPage and TotalEntries from pagination

- .gitignore
- .travis.yml
- e2e/e2e-preset.yml
- e2e/infrastructure/AccountHttp.spec.ts
- e2e/infrastructure/BlockHttp.spec.ts
- e2e/infrastructure/ChainHttp.spec.ts
- e2e/infrastructure/IntegrationTestHelper.ts
- e2e/infrastructure/Listener.spec.ts
- e2e/infrastructure/MetadataHttp.spec.ts
- e2e/infrastructure/MosaicHttp.spec.ts
- e2e/infrastructure/MultisigAccounts.spec.ts
- e2e/infrastructure/NamespaceHttp.spec.ts
- e2e/infrastructure/NetworkHttp.spec.ts
- e2e/infrastructure/NodeHttp.spec.ts
- e2e/infrastructure/PersistentHarvesting.spec.ts
- e2e/infrastructure/ReceiptHttp.spec.ts
- e2e/infrastructure/RestrictionHttp.spec.ts
- e2e/infrastructure/TransactionHttp.spec.ts
- e2e/infrastructure/UnresolvedMapping.spec.ts
- e2e/service/AccountService.spec.ts
- e2e/service/BlockService.spec.ts
- e2e/service/MetadataTransactionService.spec.ts
- e2e/service/MosaicRestrictionTransactionService.spec.ts
- e2e/service/MosaicService.spec.ts
- e2e/service/TransactionService.spec.ts
- e2e/service/TransactionService_AggregateBonded.spec.ts
- package-lock.json
- package.json
- test/infrastructure/RepositoryFactory.spec.ts
Added symbol-bootstrap to e2e tests. 
Not all the e2e tests are working, but the infrastructure is now there. Once merged, we need to start fixing the broken e2e tests.
The `e2e` branch is special, like `main` or `release`. It tells Travis to run the e2e tests. These tests can take like an hour to run, so not really practical for PR or main builds atm. In the future, when we want to e2e, we can push main branch into e2e branch. Travis will do the heavy lifting
> Symbol-bootstrap integration for e2e

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/model/transaction/Deadline.ts
- test/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- test/model/transaction/Deadline.spec.ts
> Return default (MIN) local datetime deadline value from embedded transaction

- e2e/infrastructure/PersistentHarvesting.spec.ts
- e2e/infrastructure/SecretLockHttp.spec.ts
- e2e/service/AccountService.spec.ts
- e2e/service/BlockService.spec.ts
- e2e/service/TransactionService.spec.ts
- e2e/service/TransactionService_AggregateBonded.spec.ts
- package-lock.json
- package.json
- src/service/BlockService.ts
- test/service/BlockService.spec.ts
> Added merkle hash calculation for block transactions

- src/model/transaction/AggregateTransaction.ts
- test/model/transaction/AggregateTransaction.spec.ts
`AggregateTransaction.setMaxFeeForAggregate` is using `96` as the increased size per co-signature, which is `32 (public key) + 64 (signature)`. The correct size should be `8 (version) + 32 (public key) + 64 (signature) = 104`.
`symbol-sdk-java` is setting the correct number.
https://github.com/nemtech/symbol-sdk-java/blob/2274c70718bbf0ec608ad84df3f2062a5b6c99c3/sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/AggregateTransactionFactory.java#L34
> Consider the size of version in AggregateTransaction.setMaxFeeForAggregate

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/model/message/Message.ts
- src/model/message/MessageFactory.ts
- src/model/message/MessageType.ts
- src/model/message/PersistentHarvestingDelegationMessage.ts
- src/model/message/RawMessage.ts
- src/model/message/index.ts
- src/model/transaction/TransferTransaction.ts
- test/core/utils/TransactionMapping.spec.ts
- test/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- test/model/message/PlainMessage.spec.ts
- test/model/transaction/CosignatureTransaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
Fixes https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/704.
Also, the new EmtpyMessage is a real Empty message without the 00 prefix (like java and server when creating transfer transactions)
The Message.payload is confusing, sometimes is an hex, sometime is plain text, sometime is a encrypted text. I would like to improve this but probably in a later PR.
> PersistentDelegationRequestTransaction message bug fix

- e2e/infrastructure/NodeHttp.spec.ts
- package-lock.json
- package.json
- src/infrastructure/NodeHttp.ts
- src/infrastructure/NodeRepository.ts
- src/infrastructure/RepositoryFactory.ts
- src/infrastructure/RepositoryFactoryConfig.ts
- src/infrastructure/RepositoryFactoryHttp.ts
- src/model/node/NodeInfo.ts
- test/infrastructure/NodeHttp.spec.ts
- test/infrastructure/RepositoryFactory.spec.ts
- Cache nodePublicKey in RepoFactory
- Added nodePublicKey in NodeInfo
- Removed peer param in unlockedAccount
> Added node public key

- e2e/infrastructure/Listener.spec.ts
- src/infrastructure/IListener.ts
- src/infrastructure/Listener.ts
Resolve transaction notifications with unresolved address.
> All transaction related notification should take an unresolved address

- src/core/utils/DtoMapping.ts
`MerkleStateInfoDTO` is exported directly from `symbol-openapi-typescript-fetch-client`.
Also, the compiled `d.ts` contains `import { MerkleStateInfoDTO } from 'symbol-openapi-typescript-fetch-client/src/models/index'`, so it refers to the code before compilation.
> fix import path

- e2e/infrastructure/Listener.spec.ts
- e2e/infrastructure/TransactionHttp.spec.ts
- src/infrastructure/IListener.ts
- src/infrastructure/Listener.ts
- src/infrastructure/NamespaceHttp.ts
- src/infrastructure/NamespaceRepository.ts
- src/infrastructure/RepositoryFactoryHttp.ts
- test/infrastructure/Listener.spec.ts
- Subscribe to multisig account from cosigner 
- Fixed #751
> Notification multisig

- package-lock.json
- package.json
- src/model/node/NodeVersion.ts
- src/model/node/index.ts
- test/model/node/NodeVersion.spec.ts
> Add node version model

- package-lock.json
- package.json
> Fix missing utf8 dependency

- package-lock.json
- src/model/node/NodeTime.ts
- src/model/transaction/Deadline.ts
- src/service/DeadlineService.ts
- test/service/DeadlineService.spec.ts
fix: sendTimeStamp and receiveTimeStamp are not optional, repository validate them
This feature is to help the wallet or other clients with system time sync issues like
https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1490
> feat: DeadlineService

- src/model/transaction/Transaction.ts
- test/model/transaction/Transaction.spec.ts
This PR is a proposal of breaking down the` Transaction.signWith` method into smaller methods(corresponding to the steps)
There are three parts of signing:
1- Preparing the byte array
2- Signing the byte array with private key (this happens on hardware wallet in some cases)
3- Preparing the signed raw tx - payload 
4- Return SignedTransaction object
> feat: transaction signWith method broken into smaller  methods

- src/core/utils/DtoMapping.ts
- src/core/utils/UnresolvedMapping.ts
- src/infrastructure/AccountHttp.ts
- src/infrastructure/BlockHttp.ts
- src/infrastructure/HashLockHttp.ts
- src/infrastructure/Listener.ts
- src/infrastructure/MetadataHttp.ts
- src/infrastructure/MosaicHttp.ts
- src/infrastructure/MultisigHttp.ts
- src/infrastructure/NamespaceHttp.ts
- src/infrastructure/RestrictionMosaicHttp.ts
- src/infrastructure/SecretLockHttp.ts
- src/infrastructure/receipt/CreateReceiptFromDTO.ts
- src/model/transaction/AddressAliasTransaction.ts
- test/core/utils/DtoMapping.spec.ts
- test/core/utils/UnresolvedMapping.spec.ts
- test/infrastructure/receipt/CreateReceiptFromDTO.spec.ts
- test/model/receipt/Receipt.spec.ts
This is the SDK side of https://github.com/symbol/catapult-rest/pull/611
The new rest mappers will accept both encoded/hex and plain/decoded addresses. It will buffer the migration allowing the SDK rest client to be compatible with old and new rests. Eventually, we should only allow base32 addresses. Apps only need to upgrade the SDK, no code change is required.
A migration plan could be:
- Merge and release this SDK fix.
- Merge and release the Rest fix.
- Upgrade SDKs in all our apps (CLIs, explorers, wallets, etc). Release the apps. The apps will be old and new rest compatible. 
- Migrate testnet, mainnet, and community nodes to the new rest when possible.  
No flag is required. 
Related issues:
https://github.com/symbol/symbol-sdk-typescript-javascript/issues/801 …
> Allow rest base 32 addresses

- .travis.yml
- package-lock.json
- package.json
I'm doing several upgrades, first upgrade is node js 12. The rest, typescript 4, eslint 8, rxjs 7 will follow
> fix: node js upgrade to 12

- e2e/infrastructure/MetadataHttp.spec.ts
- e2e/infrastructure/TransactionHttp.spec.ts
- e2e/infrastructure/UnresolvedMapping.spec.ts
- e2e/service/MetadataTransactionService.spec.ts
- e2e/service/TransactionService.spec.ts
- src/core/format/Convert.ts
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- src/model/transaction/AccountMetadataTransaction.ts
- src/model/transaction/MosaicMetadataTransaction.ts
- src/model/transaction/NamespaceMetadataTransaction.ts
- src/service/MetadataTransactionService.ts
- test/core/format/Convert.spec.ts
- test/core/utils/TransactionMapping.spec.ts
- test/core/utils/TransactionMappingWithSignatures.spec.ts
- test/model/transaction/AccountMetadataTransaction.spec.ts
- test/model/transaction/MosaicMetadataTransaction.spec.ts
- test/model/transaction/NamespaceMetadataTransaction.spec.ts
- test/service/MetadataTransactionservice.spec.ts
fixes #834 
from #834 
> There is a problem when we want to replace the non-ascii text value in metadata with ascii one. In such a case we receive the error:
Failure_Metadata_Value_Size_Delta_Mismatch
We noticed that `value` field in the Metadata Transactions(`AccountMetadataTransaction`, `NamespaceMetadataTransaction`, `MosaicMetadataTransaction`) has the type `string`.
This was the root cause of the issue, since the `value` field was meant to be a difference between the previous and the new value in _bytes_, converting the difference to first `string` and then to `byte[]` was resulting in loss of bytes and therefore sending wrong information to the `catapult-rest`.
In order to fix this, we:
* Removed the `rstr2utf8` method which was used during the conversion, fixing _insert_ part of …
> fix: metadata value non-ascii utf8 encoding issue fixed

- src/core/crypto/Utilities.ts
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/infrastructure/transaction/SerializeTransactionToJSON.ts
- test/infrastructure/SerializeTransactionToJSON.spec.ts
- test/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- test/infrastructure/transaction/ValidateTransaction.ts
After the type of `Metadata.value` is changed from `string` to `byte array`,  we noticed that JSON serialization and deserialization started to fail.
`byte array` is now being converted to `hex` value during serialization and converted back during deserialization.
> fix: metadata value ser/deser is fixed

- CHANGELOG.md
- package-lock.json
- package.json
Since the change in the `MetadataTransaction.value` type is a breaking change and requires small code change in the clients, this release is prepared as a major release(v1.0.3 -> **v2.0.0**)
* prep for release v2.0.0
* updated CHANGELOG.md
**Milestone**: Symbol Mainnet
---|---|---
SDK Core| v2.0.0 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v1.0.1 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
- **[BREAKING CHANGE]** The type of `value` field in `AccountMetadataTransaction`, `MosaicMetadataTransaction`, `NamespaceMetadataTransaction` classes is changed from `string` to …
> prep for release v2.0.0, updated CHANGELOG.md

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- src/model/transaction/AggregateTransactionInfo.ts
- src/model/transaction/TransactionInfo.ts
- test/infrastructure/Listener.spec.ts
- test/infrastructure/TransactionHttp.spec.ts
- test/infrastructure/transaction/CreateTransactionFromDTO.spec.ts
- test/model/transaction/AggregateTransaction.spec.ts
- test/model/transaction/CosignatureTransaction.spec.ts
- test/model/transaction/Transaction.spec.ts
- test/model/transaction/TransferTransaction.spec.ts
- test/service/BlockService.spec.ts
- The SDK transaction DTO was missing some info such as meta's `timestamp` and `feeMultiplier`.
- added missing properties in transaction dto
```
{
...
feeMultiplier: number,
timestamp: UInt64
}
```
- update all the unit test
> task: fix missing tx meta

- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- test/infrastructure/TransactionHttp.spec.ts
- REST is not returned ` timestamp` and `feeMultiplier` in unconfirmed / partial / Listener, It caused SDK transaction DTO throw error when the value is undefined.
- added bullish coalescing operator to handle `timestamp` and `feeMultiplier`, when value is undefined, it returns `0`
> task: add nullish coalescing operator to handle undefine meta properties

- CHANGELOG.md
[Bug] [#843](https://github.com/symbol/symbol-sdk-typescript-javascript/pull/843): Handle transaction meta's timestamp and feeMultiplier when value is undefined.
> docs: update change log 2.0.2

- CHANGELOG.md
- src/infrastructure/transaction/CreateTransactionFromDTO.ts
- test/infrastructure/TransactionHttp.spec.ts
Releasing `v2.0.2`.
**Milestone**: Symbol Mainnet
---|---|---
SDK Core| v2.0.2 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v1.0.1 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
[Bug] [#843](https://github.com/symbol/symbol-sdk-typescript-javascript/pull/843): Handle transaction meta's timestamp and feeMultiplier when value is undefined.
> Release v2.0.2

- CHANGELOG.md
- package-lock.json
Releasing v2.0.3
**Milestone**: Symbol Mainnet
---|---|---
SDK Core| v2.0.3 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v1.0.2 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
- Bumped AggregateTransaction version to V2. Note that the ability to create or broadcast V1 aggregate transactions has been removed.
- [Bug] Fixed incorrect Merkle hash calculation for aggregate transactions.
- [Bug] Fixed the calculation of embedded transaction (also known as inner aggregate transaction) hashes without padding.
> Release v2.0.3

- CONTRIBUTING.md
- README.md
- src/model/mosaic/MosaicInfo.ts
- src/model/transaction/MosaicDefinitionTransaction.ts
- test/model/transaction/MosaicDefinitionTransaction.spec.ts
The revocable attribute is missing when generating a MethodDefinitionTransaction from a payload. Check #849
MethodDefinitionTransaction is initializing now all mosaic flags when creating MosaicDefinitionTransaction from the payload.
> Fix mosaic definition transaction from payload method

- src/model/transaction/TransferTransaction.ts
- test/model/transaction/TransferTransaction.spec.ts
The message is not correctly encoded when creating a `TransferTransaction` with `RawMessage`.
The `Uint8Array` is encoded to a hex string during `RawMessage.create()`.
Then in the `getMessageBuffer()` of `TransferTransaction` the hex string (considered as a plain utf-8 text string) is converted to hex string again.
Also, an extra 0xFF byte is added at the beginning of the raw message.
- Remove double conversion of `RawMessage.payload` to hex in `TransferTransaction.getMessageBuffer()`, since the payload is already in hex.
- Remove adding an extra byte to the beginning of the message.
> fix: raw message encoding in TransferTransaction

- CHANGELOG.md
- package.json
- src/model/transaction/TransferTransaction.ts
- test/model/transaction/TransferTransaction.spec.ts
---|---|---
SDK Core| v2.0.5 | [symbol-sdk](https://www.npmjs.com/package/symbol-sdk)
Catbuffer | v1.0.2 | [catbuffer-typescript](https://www.npmjs.com/package/catbuffer-typescript)
- [Bug] [853](https://github.com/symbol/symbol-sdk-typescript-javascript/pull/853): Fixed encoding of raw messages in TransferTransaction.
> Release v2.0.5
